import type { ClayHourlyBackfillRequest, ClayReportContext, CreateClayColumnRequest, CreateClayOperationLogRequest, PatchClayReportRequest, UpdateClayColumnRequest } from '@qc/contracts';
import type { AuthPrincipal, ClayReportRecord, ClayReportRepository, MasterRepository } from '@qc/domain';
import { AppError, forbidden, notFound } from '../../lib/errors';

const isQc=(p:AuthPrincipal)=>['QC_ANALYST','SUPERVISOR_ADMIN'].includes(p.role);
const canWork=(p:AuthPrincipal)=>isQc(p)||p.role==='CRUSHER_OPERATOR';
const iso=(d:Date|null)=>d?.toISOString()??null;
const clean=(v:string|null|undefined)=>v?.trim()||null;

function assertColumnShape(value:{inputMode:string;vendorId:string|null;sourceId:string|null;vendorNameSnapshot:string|null;sourceNameSnapshot:string|null}){
  if(value.inputMode==='MASTER'&&!value.vendorId&&!value.sourceId)throw new AppError(400,'CLAY_MASTER_REFERENCE_REQUIRED','Mode master memerlukan vendor atau sumber dari master data.');
  if(value.inputMode==='MANUAL'&&!clean(value.vendorNameSnapshot)&&!clean(value.sourceNameSnapshot))throw new AppError(400,'CLAY_MANUAL_NAME_REQUIRED','Mode manual memerlukan nama vendor atau sumber.');
  if(value.inputMode!=='BUFFER'&&!value.vendorId&&!value.sourceId&&!clean(value.vendorNameSnapshot)&&!clean(value.sourceNameSnapshot))throw new AppError(400,'CLAY_COLUMN_LABEL_REQUIRED','Kolom Clay memerlukan vendor atau sumber.');
}

export function createClayReportService(repository:ClayReportRepository,master:MasterRepository){
  function assertWork(p:AuthPrincipal){if(!canWork(p))throw forbidden('Laporan utama Clay hanya dapat dikelola operator crusher, QC Analyst, atau Supervisor/Admin.');}
  function assertQc(p:AuthPrincipal){if(!isQc(p))throw forbidden('Aksi ini khusus QC Analyst atau Supervisor/Admin.');}
  function assertCrusherScope(p:AuthPrincipal,crusherId:string){if(p.role==='CRUSHER_OPERATOR'&&(!p.crusherIds.length||!p.crusherIds.includes(crusherId)))throw forbidden('Crusher di luar scope operator.');}
  async function reportOrThrow(id:string){const report=await repository.findReport(id);if(!report)throw notFound('Laporan Clay tidak ditemukan.');return report;}
  function assertDraft(report:ClayReportRecord){if(report.status!=='DRAFT')throw new AppError(409,'CLAY_REPORT_LOCKED','Laporan Clay hanya dapat diubah saat DRAFT.');}
  async function contextValid(p:AuthPrincipal,context:ClayReportContext){assertWork(p);assertCrusherScope(p,context.crusherId);const crusher=await master.findCrusherById(context.crusherId);if(!crusher||!crusher.active)throw notFound('Crusher tidak ditemukan atau nonaktif.');if(crusher.materialKind!=='CL')throw new AppError(400,'MATERIAL_KIND_MISMATCH','Workflow ini hanya untuk Clay.');}
  async function dto(report:ClayReportRecord){const[columns,operationLogs,hourly]=await Promise.all([repository.listColumns(report.id),repository.listOperationLogs(report.id),repository.listHourly(report.id)]);const totalRetase=hourly.reduce((sum,x)=>sum+x.retase,0);const totalTonnage=hourly.reduce((sum,x)=>sum+x.tonnage,0);return{
    ...report,operatorUserId:undefined,updatedBy:undefined,submittedBy:undefined,approvedBy:undefined,
    productionTonnage:report.productionTonnage,runningMinutes:report.runningMinutes,totalRunningMinutes:report.totalRunningMinutes,capacityTph:report.capacityTph,stockPercent:report.stockPercent,
    submittedAt:iso(report.submittedAt),approvedAt:iso(report.approvedAt),createdAt:report.createdAt.toISOString(),updatedAt:report.updatedAt.toISOString(),
    columns:columns.map(x=>({...x,createdBy:undefined,updatedBy:undefined,createdAt:x.createdAt.toISOString(),updatedAt:x.updatedAt.toISOString()})),
    operationLogs:operationLogs.map(x=>({...x,createdBy:undefined,createdAt:x.createdAt.toISOString()})),hourly,totalRetase,totalTonnage,
  };}
  async function audit(p:AuthPrincipal,action:string,entityType:string,entityId:string,before:unknown,after:unknown,reason?:string,requestId?:string){await repository.appendAudit({actorUserId:p.userId,actorRoleSnapshot:p.role,action,entityType,entityId,beforeJson:before,afterJson:after,reason:reason??null,requestId});}

  return{
    async current(p:AuthPrincipal,context:ClayReportContext){await contextValid(p,context);const report=await repository.findCurrent(context);if(!report)throw notFound('Laporan Clay untuk konteks ini belum dibuat.');return dto(report);},
    async get(p:AuthPrincipal,id:string){assertWork(p);const report=await reportOrThrow(id);assertCrusherScope(p,report.crusherId);return dto(report);},
    async ensure(p:AuthPrincipal,context:ClayReportContext,requestId?:string){await contextValid(p,context);let report=await repository.findCurrent(context);if(!report){report=await repository.createReport({...context,operatorUserId:p.role==='CRUSHER_OPERATOR'?p.userId:null,operatorNameSnapshot:p.role==='CRUSHER_OPERATOR'?p.displayName:null,createdBy:p.userId});await audit(p,'CREATE','CLAY_SHIFT_REPORT',report.id,null,report,undefined,requestId);}return dto(report);},
    async patch(p:AuthPrincipal,id:string,input:PatchClayReportRequest,requestId?:string){assertQc(p);const before=await reportOrThrow(id);assertDraft(before);const patch=Object.fromEntries(Object.entries(input).filter(([,v])=>v!==undefined)) as Parameters<ClayReportRepository['updateReport']>[1];patch.updatedBy=p.userId;const updated=await repository.updateReport(id,patch);if(!updated)throw notFound();await audit(p,'UPDATE','CLAY_SHIFT_REPORT',id,before,updated,undefined,requestId);return dto(updated);},
    async createColumn(p:AuthPrincipal,reportId:string,input:CreateClayColumnRequest,requestId?:string){assertWork(p);const report=await reportOrThrow(reportId);assertCrusherScope(p,report.crusherId);assertDraft(report);
      let vendorName=clean(input.vendorNameSnapshot),sourceName=clean(input.sourceNameSnapshot);
      if(input.vendorId){const vendor=await master.findVendorById(input.vendorId);if(!vendor||!vendor.active||!vendor.materialKinds.includes('CL'))throw new AppError(400,'CLAY_VENDOR_INVALID','Vendor tidak aktif atau bukan master Clay.');vendorName=vendor.name;}
      if(input.sourceId){const source=await master.findSourceById(input.sourceId);if(!source||!source.active||source.materialKind!=='CL')throw new AppError(400,'CLAY_SOURCE_INVALID','Source tidak aktif atau bukan master Clay.');sourceName=source.name;}
      if(input.pileId){const pile=await master.findPileById(input.pileId);if(!pile||!pile.active||pile.materialKind!=='CL')throw new AppError(400,'CLAY_PILE_INVALID','Pile tidak aktif atau bukan master Clay.');}
      const created=await repository.createColumn({reportId,displayOrder:input.displayOrder,vendorId:input.vendorId??null,sourceId:input.sourceId??null,pileId:input.pileId??null,vendorNameSnapshot:vendorName,sourceNameSnapshot:sourceName,headerPrimary:input.headerPrimary.trim(),headerSecondary:clean(input.headerSecondary),inputMode:input.inputMode,status:p.role==='CRUSHER_OPERATOR'?'PROVISIONAL':'CONFIRMED',tonPerRetaseSnapshot:input.tonPerRetaseSnapshot??null,createdBy:p.userId});await audit(p,'CREATE','CLAY_REPORT_COLUMN',created.id,null,created,undefined,requestId);return dto(report);},
    async updateColumn(p:AuthPrincipal,reportId:string,columnId:string,input:UpdateClayColumnRequest,requestId?:string){assertWork(p);const report=await reportOrThrow(reportId);assertCrusherScope(p,report.crusherId);assertDraft(report);const before=await repository.findColumn(columnId);if(!before||before.reportId!==reportId)throw notFound('Kolom Clay tidak ditemukan.');if(p.role==='CRUSHER_OPERATOR'&&(before.status!=='PROVISIONAL'||input.status!==undefined))throw forbidden('Operator hanya dapat memperbaiki kolom provisional; konfirmasi dilakukan QC/Supervisor.');
      const patch=Object.fromEntries(Object.entries(input).filter(([key,v])=>key!=='reason'&&v!==undefined)) as Parameters<ClayReportRepository['updateColumn']>[1];patch.updatedBy=p.userId;
      if(input.vendorId!==undefined){const vendor=input.vendorId?await master.findVendorById(input.vendorId):null;if(input.vendorId&&(!vendor||!vendor.active||!vendor.materialKinds.includes('CL')))throw new AppError(400,'CLAY_VENDOR_INVALID','Vendor bukan master Clay.');patch.vendorNameSnapshot=vendor?.name??clean(input.vendorNameSnapshot);}
      if(input.sourceId!==undefined){const source=input.sourceId?await master.findSourceById(input.sourceId):null;if(input.sourceId&&(!source||!source.active||source.materialKind!=='CL'))throw new AppError(400,'CLAY_SOURCE_INVALID','Source bukan master Clay.');patch.sourceNameSnapshot=source?.name??clean(input.sourceNameSnapshot);}
      if(input.pileId){const pile=await master.findPileById(input.pileId);if(!pile||!pile.active||pile.materialKind!=='CL')throw new AppError(400,'CLAY_PILE_INVALID','Pile tidak aktif atau bukan master Clay.');}
      assertColumnShape({...before,...patch});
      const updated=await repository.updateColumn(columnId,patch);await audit(p,'UPDATE','CLAY_REPORT_COLUMN',columnId,before,updated,input.reason,requestId);return dto(report);},
    async addLog(p:AuthPrincipal,reportId:string,input:CreateClayOperationLogRequest,requestId?:string){assertWork(p);const report=await reportOrThrow(reportId);assertCrusherScope(p,report.crusherId);assertDraft(report);const log=await repository.createOperationLog({reportId,displayOrder:input.displayOrder,startTime:input.startTime??null,endTime:input.endTime??null,category:input.category,description:input.description.trim(),createdBy:p.userId});await audit(p,'CREATE','CLAY_OPERATION_LOG',log.id,null,log,undefined,requestId);return dto(report);},
    async backfill(p:AuthPrincipal,reportId:string,input:ClayHourlyBackfillRequest,requestId?:string){assertQc(p);const report=await reportOrThrow(reportId);assertDraft(report);const column=await repository.findColumn(input.columnId);if(!column||column.reportId!==reportId||column.status==='INACTIVE')throw notFound('Kolom Clay aktif tidak ditemukan.');await repository.appendHourly({requestId:input.requestId,batchId:input.batchId??input.requestId,report,column,eventAt:new Date(input.eventAt),delta:input.delta,reason:input.reason,createdBy:p.userId});await audit(p,'BACKFILL','CLAY_HOURLY_RETASE',reportId,null,{columnId:column.id,eventAt:input.eventAt,delta:input.delta,batchId:input.batchId??input.requestId},input.reason,requestId);return dto(report);},
    async submit(p:AuthPrincipal,id:string,requestId?:string){assertQc(p);const report=await reportOrThrow(id);assertDraft(report);const columns=await repository.listColumns(id);if(!columns.some(x=>x.status==='CONFIRMED'))throw new AppError(400,'CLAY_COLUMN_REQUIRED','Minimum satu kolom terkonfirmasi wajib sebelum submit.');if(columns.some(x=>x.status==='PROVISIONAL'))throw new AppError(400,'CLAY_PROVISIONAL_COLUMNS','Konfirmasi atau nonaktifkan semua kolom provisional.');const hourly=await repository.listHourly(id);if(hourly.some(x=>x.retase<0))throw new AppError(400,'CLAY_NEGATIVE_RETASE','Retase per jam tidak boleh negatif.');const updated=await repository.updateReport(id,{status:'SUBMITTED',submittedBy:p.userId,submittedAt:new Date(),updatedBy:p.userId});await audit(p,'SUBMIT','CLAY_SHIFT_REPORT',id,report,updated,undefined,requestId);return dto(updated!);},
    async approve(p:AuthPrincipal,id:string,requestId?:string){if(p.role!=='SUPERVISOR_ADMIN')throw forbidden();const report=await reportOrThrow(id);if(report.status!=='SUBMITTED')throw new AppError(409,'CLAY_REPORT_STATE','Hanya laporan SUBMITTED yang dapat disetujui.');const updated=await repository.updateReport(id,{status:'APPROVED',approvedBy:p.userId,approvedAt:new Date(),updatedBy:p.userId});await audit(p,'APPROVE','CLAY_SHIFT_REPORT',id,report,updated,undefined,requestId);return dto(updated!);},
    async reopen(p:AuthPrincipal,id:string,reason:string|undefined,requestId?:string){if(p.role!=='SUPERVISOR_ADMIN')throw forbidden();if(!reason)throw new AppError(400,'REASON_REQUIRED','Alasan buka ulang wajib.');const report=await reportOrThrow(id);if(!['SUBMITTED','APPROVED'].includes(report.status))throw new AppError(409,'CLAY_REPORT_STATE','Laporan tidak dapat dibuka ulang.');const updated=await repository.updateReport(id,{status:'DRAFT',revisionReason:reason,submittedBy:null,submittedAt:null,approvedBy:null,approvedAt:null,updatedBy:p.userId});await audit(p,'REOPEN','CLAY_SHIFT_REPORT',id,report,updated,reason,requestId);return dto(updated!);},
  };
}
export type ClayReportService=ReturnType<typeof createClayReportService>;
