/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedClayReportRouteImport } from './routes/_authenticated/clay-report'
import { Route as AuthenticatedMasterDataRouteImport } from './routes/_authenticated/master-data'
import { Route as AuthenticatedPetaMutuRouteImport } from './routes/_authenticated/peta-mutu'
import { Route as AuthenticatedQcReportsRouteImport } from './routes/_authenticated/qc-reports'
import { Route as AuthenticatedQcWorkbenchRouteImport } from './routes/_authenticated/qc-workbench'
import { Route as AuthenticatedRawSamplesRouteImport } from './routes/_authenticated/raw-samples'
import { Route as AuthenticatedReconciliationRouteImport } from './routes/_authenticated/reconciliation'
import { Route as AuthenticatedRetaseCounterRouteImport } from './routes/_authenticated/retase-counter'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedUserManagementRouteImport } from './routes/_authenticated/user-management'
import { Route as AuthenticatedVendorShiftReportRouteImport } from './routes/_authenticated/vendor-shift-report'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClayReportRoute = AuthenticatedClayReportRouteImport.update({
  id: '/clay-report',
  path: '/clay-report',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMasterDataRoute = AuthenticatedMasterDataRouteImport.update({
  id: '/master-data',
  path: '/master-data',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPetaMutuRoute = AuthenticatedPetaMutuRouteImport.update({
  id: '/peta-mutu',
  path: '/peta-mutu',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQcReportsRoute = AuthenticatedQcReportsRouteImport.update({
  id: '/qc-reports',
  path: '/qc-reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQcWorkbenchRoute =
  AuthenticatedQcWorkbenchRouteImport.update({
    id: '/qc-workbench',
    path: '/qc-workbench',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRawSamplesRoute = AuthenticatedRawSamplesRouteImport.update({
  id: '/raw-samples',
  path: '/raw-samples',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReconciliationRoute =
  AuthenticatedReconciliationRouteImport.update({
    id: '/reconciliation',
    path: '/reconciliation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRetaseCounterRoute =
  AuthenticatedRetaseCounterRouteImport.update({
    id: '/retase-counter',
    path: '/retase-counter',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUserManagementRoute =
  AuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVendorShiftReportRoute =
  AuthenticatedVendorShiftReportRouteImport.update({
    id: '/vendor-shift-report',
    path: '/vendor-shift-report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/clay-report': typeof AuthenticatedClayReportRoute
  '/master-data': typeof AuthenticatedMasterDataRoute
  '/peta-mutu': typeof AuthenticatedPetaMutuRoute
  '/qc-reports': typeof AuthenticatedQcReportsRoute
  '/qc-workbench': typeof AuthenticatedQcWorkbenchRoute
  '/raw-samples': typeof AuthenticatedRawSamplesRoute
  '/reconciliation': typeof AuthenticatedReconciliationRoute
  '/retase-counter': typeof AuthenticatedRetaseCounterRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/user-management': typeof AuthenticatedUserManagementRoute
  '/vendor-shift-report': typeof AuthenticatedVendorShiftReportRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/clay-report': typeof AuthenticatedClayReportRoute
  '/master-data': typeof AuthenticatedMasterDataRoute
  '/peta-mutu': typeof AuthenticatedPetaMutuRoute
  '/qc-reports': typeof AuthenticatedQcReportsRoute
  '/qc-workbench': typeof AuthenticatedQcWorkbenchRoute
  '/raw-samples': typeof AuthenticatedRawSamplesRoute
  '/reconciliation': typeof AuthenticatedReconciliationRoute
  '/retase-counter': typeof AuthenticatedRetaseCounterRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/user-management': typeof AuthenticatedUserManagementRoute
  '/vendor-shift-report': typeof AuthenticatedVendorShiftReportRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/clay-report': typeof AuthenticatedClayReportRoute
  '/_authenticated/master-data': typeof AuthenticatedMasterDataRoute
  '/_authenticated/peta-mutu': typeof AuthenticatedPetaMutuRoute
  '/_authenticated/qc-reports': typeof AuthenticatedQcReportsRoute
  '/_authenticated/qc-workbench': typeof AuthenticatedQcWorkbenchRoute
  '/_authenticated/raw-samples': typeof AuthenticatedRawSamplesRoute
  '/_authenticated/reconciliation': typeof AuthenticatedReconciliationRoute
  '/_authenticated/retase-counter': typeof AuthenticatedRetaseCounterRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/user-management': typeof AuthenticatedUserManagementRoute
  '/_authenticated/vendor-shift-report': typeof AuthenticatedVendorShiftReportRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/clay-report'
    | '/master-data'
    | '/peta-mutu'
    | '/qc-reports'
    | '/qc-workbench'
    | '/raw-samples'
    | '/reconciliation'
    | '/retase-counter'
    | '/security'
    | '/user-management'
    | '/vendor-shift-report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/clay-report'
    | '/master-data'
    | '/peta-mutu'
    | '/qc-reports'
    | '/qc-workbench'
    | '/raw-samples'
    | '/reconciliation'
    | '/retase-counter'
    | '/security'
    | '/user-management'
    | '/vendor-shift-report'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/clay-report'
    | '/_authenticated/master-data'
    | '/_authenticated/peta-mutu'
    | '/_authenticated/qc-reports'
    | '/_authenticated/qc-workbench'
    | '/_authenticated/raw-samples'
    | '/_authenticated/reconciliation'
    | '/_authenticated/retase-counter'
    | '/_authenticated/security'
    | '/_authenticated/user-management'
    | '/_authenticated/vendor-shift-report'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clay-report': {
      id: '/_authenticated/clay-report'
      path: '/clay-report'
      fullPath: '/clay-report'
      preLoaderRoute: typeof AuthenticatedClayReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master-data': {
      id: '/_authenticated/master-data'
      path: '/master-data'
      fullPath: '/master-data'
      preLoaderRoute: typeof AuthenticatedMasterDataRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/peta-mutu': {
      id: '/_authenticated/peta-mutu'
      path: '/peta-mutu'
      fullPath: '/peta-mutu'
      preLoaderRoute: typeof AuthenticatedPetaMutuRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qc-reports': {
      id: '/_authenticated/qc-reports'
      path: '/qc-reports'
      fullPath: '/qc-reports'
      preLoaderRoute: typeof AuthenticatedQcReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qc-workbench': {
      id: '/_authenticated/qc-workbench'
      path: '/qc-workbench'
      fullPath: '/qc-workbench'
      preLoaderRoute: typeof AuthenticatedQcWorkbenchRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/raw-samples': {
      id: '/_authenticated/raw-samples'
      path: '/raw-samples'
      fullPath: '/raw-samples'
      preLoaderRoute: typeof AuthenticatedRawSamplesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reconciliation': {
      id: '/_authenticated/reconciliation'
      path: '/reconciliation'
      fullPath: '/reconciliation'
      preLoaderRoute: typeof AuthenticatedReconciliationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/retase-counter': {
      id: '/_authenticated/retase-counter'
      path: '/retase-counter'
      fullPath: '/retase-counter'
      preLoaderRoute: typeof AuthenticatedRetaseCounterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/user-management': {
      id: '/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof AuthenticatedUserManagementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vendor-shift-report': {
      id: '/_authenticated/vendor-shift-report'
      path: '/vendor-shift-report'
      fullPath: '/vendor-shift-report'
      preLoaderRoute: typeof AuthenticatedVendorShiftReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedClayReportRoute: typeof AuthenticatedClayReportRoute
  AuthenticatedMasterDataRoute: typeof AuthenticatedMasterDataRoute
  AuthenticatedPetaMutuRoute: typeof AuthenticatedPetaMutuRoute
  AuthenticatedQcReportsRoute: typeof AuthenticatedQcReportsRoute
  AuthenticatedQcWorkbenchRoute: typeof AuthenticatedQcWorkbenchRoute
  AuthenticatedRawSamplesRoute: typeof AuthenticatedRawSamplesRoute
  AuthenticatedReconciliationRoute: typeof AuthenticatedReconciliationRoute
  AuthenticatedRetaseCounterRoute: typeof AuthenticatedRetaseCounterRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedUserManagementRoute: typeof AuthenticatedUserManagementRoute
  AuthenticatedVendorShiftReportRoute: typeof AuthenticatedVendorShiftReportRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedClayReportRoute: AuthenticatedClayReportRoute,
  AuthenticatedMasterDataRoute: AuthenticatedMasterDataRoute,
  AuthenticatedPetaMutuRoute: AuthenticatedPetaMutuRoute,
  AuthenticatedQcReportsRoute: AuthenticatedQcReportsRoute,
  AuthenticatedQcWorkbenchRoute: AuthenticatedQcWorkbenchRoute,
  AuthenticatedRawSamplesRoute: AuthenticatedRawSamplesRoute,
  AuthenticatedReconciliationRoute: AuthenticatedReconciliationRoute,
  AuthenticatedRetaseCounterRoute: AuthenticatedRetaseCounterRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedUserManagementRoute: AuthenticatedUserManagementRoute,
  AuthenticatedVendorShiftReportRoute: AuthenticatedVendorShiftReportRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
