services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: qc_raw_material
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - qc_pgdata:/var/lib/postgresql/data
volumes:
  qc_pgdata:
