import { customType,index,integer,jsonb,pgTable,text,timestamp,uniqueIndex,uuid } from 'drizzle-orm/pg-core';
import { users,vendors } from './iam';
import { crushers,shifts } from './master';
import { loadingAssignmentAas } from './vendor-operation';
import { date } from 'drizzle-orm/pg-core';
const bytea=customType<{data:Buffer}>({dataType:()=> 'bytea'});
export const crusherReportImports=pgTable('crusher_report_imports',{
  id:uuid('id').primaryKey().defaultRandom(),crusherId:uuid('crusher_id').notNull().references(()=>crushers.id),fileName:text('file_name').notNull(),sha256:text('sha256').notNull(),status:text('status').notNull().default('QUEUED'),revision:integer('revision').notNull().default(1),parsedJson:jsonb('parsed_json'),draftJson:jsonb('draft_json'),issuesJson:jsonb('issues_json').notNull().default([]),parserVersion:text('parser_version'),templateVersion:text('template_version'),error:text('error'),leaseToken:uuid('lease_token'),startedAt:timestamp('started_at',{withTimezone:true}),completedAt:timestamp('completed_at',{withTimezone:true}),createdBy:uuid('created_by').notNull().references(()=>users.id),createdAt:timestamp('created_at',{withTimezone:true}).notNull().defaultNow(),confirmedBy:uuid('confirmed_by').references(()=>users.id),confirmedAt:timestamp('confirmed_at',{withTimezone:true}),
},t=>[uniqueIndex('crusher_import_hash_uq').on(t.crusherId,t.sha256)]);
export const crusherReportImportFiles=pgTable('crusher_report_import_files',{importId:uuid('import_id').primaryKey().references(()=>crusherReportImports.id),mimeType:text('mime_type').notNull(),sourceBytes:bytea('source_bytes').notNull(),alignedBytes:bytea('aligned_bytes')});
export const parserFieldObservations=pgTable('parser_field_observations',{id:uuid('id').primaryKey().defaultRandom(),importId:uuid('import_id').notNull().references(()=>crusherReportImports.id),parserRun:integer('parser_run').notNull(),fieldPath:text('field_path').notNull(),observation:jsonb('observation').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).notNull().defaultNow()});
export const parserFieldCorrections=pgTable('parser_field_corrections',{id:uuid('id').primaryKey().defaultRandom(),importId:uuid('import_id').notNull().references(()=>crusherReportImports.id),revision:integer('revision').notNull(),fieldPath:text('field_path').notNull(),predictedValue:jsonb('predicted_value'),correctedValue:jsonb('corrected_value'),createdBy:uuid('created_by').notNull().references(()=>users.id),createdAt:timestamp('created_at',{withTimezone:true}).notNull().defaultNow()});
export const crusherReports=pgTable('crusher_reports',{id:uuid('id').primaryKey().defaultRandom(),importId:uuid('import_id').notNull().unique().references(()=>crusherReportImports.id),crusherId:uuid('crusher_id').notNull().references(()=>crushers.id),reportDate:date('report_date').notNull(),shiftCode:text('shift_code').notNull().references(()=>shifts.code),timezone:text('timezone').notNull().default('Asia/Makassar'),canonicalJson:jsonb('canonical_json').notNull(),confirmedBy:uuid('confirmed_by').notNull().references(()=>users.id),confirmedAt:timestamp('confirmed_at',{withTimezone:true}).notNull().defaultNow()},t=>[uniqueIndex('crusher_report_context_uq').on(t.crusherId,t.reportDate,t.shiftCode)]);
export const crusherReportVehicleRows=pgTable('crusher_report_vehicle_rows',{id:uuid('id').primaryKey().defaultRandom(),reportId:uuid('report_id').notNull().references(()=>crusherReports.id),blockKey:text('block_key').notNull(),rowIndex:integer('row_index').notNull(),dtNo:text('dt_no').notNull(),vendorId:uuid('vendor_id').notNull().references(()=>vendors.id),assignmentAaId:uuid('assignment_aa_id').references(()=>loadingAssignmentAas.id),retase:integer('retase').notNull()},t=>[uniqueIndex('crusher_report_vehicle_rows_report_id_block_key_row_index_key').on(t.reportId,t.blockKey,t.rowIndex)]);
