import { boolean, date, index, integer, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';
import { mappingStatusEnum, materialKindEnum, retaseEventStatusEnum, retaseEventTypeEnum } from './enums';
import { users, vendors } from './iam';
import { crushers, equipment, piles, sources } from './master';
import { loadingAssignmentAas, loadingAssignments, vendorShiftReports } from './vendor-operation';
import { rawSamples } from './raw-sample';

export const retaseEvents = pgTable('retase_events', {
  id: uuid('id').primaryKey().defaultRandom(),
  requestId: uuid('request_id').notNull(),
  operationDate: date('operation_date').notNull(),
  eventTs: timestamp('event_ts', { withTimezone: true }).notNull().defaultNow(),
  shiftCode: text('shift_code').notNull(),
  crusherId: uuid('crusher_id').notNull().references(() => crushers.id, { onDelete: 'restrict' }),
  vendorId: uuid('vendor_id').references(() => vendors.id, { onDelete: 'restrict' }),
  reportId: uuid('report_id').references(() => vendorShiftReports.id, { onDelete: 'restrict' }),
  reportVersion: integer('report_version'),
  assignmentId: uuid('assignment_id').references(() => loadingAssignments.id, { onDelete: 'restrict' }),
  assignmentAaId: uuid('assignment_aa_id').references(() => loadingAssignmentAas.id, { onDelete: 'restrict' }),
  assignmentOrigin: text('assignment_origin'),
  amId: uuid('am_id').references(() => equipment.id, { onDelete: 'restrict' }),
  aaId: uuid('aa_id').references(() => equipment.id, { onDelete: 'restrict' }),
  sourceId: uuid('source_id').references(() => sources.id, { onDelete: 'restrict' }),
  pileId: uuid('pile_id').references(() => piles.id, { onDelete: 'restrict' }),
  blockSnapshot: text('block_snapshot'),
  materialKind: materialKindEnum('material_kind'),
  materialCategory: text('material_category'),
  vendorNameSnapshot: text('vendor_name_snapshot'),
  amUnitNoSnapshot: text('am_unit_no_snapshot'),
  aaUnitNoSnapshot: text('aa_unit_no_snapshot'),
  delta: integer('delta').notNull(),
  eventType: retaseEventTypeEnum('event_type').notNull(),
  status: retaseEventStatusEnum('status').notNull(),
  createdBy: uuid('created_by').notNull().references(() => users.id, { onDelete: 'restrict' }),
  reversesEventId: uuid('reverses_event_id'),
  reason: text('reason'),
  clientTs: timestamp('client_ts', { withTimezone: true }),
  resolvedBy: uuid('resolved_by').references(() => users.id, { onDelete: 'restrict' }),
  resolvedAt: timestamp('resolved_at', { withTimezone: true }),
  resolutionReason: text('resolution_reason'),
}, (t) => [
  uniqueIndex('retase_request_id_uq').on(t.requestId),
  uniqueIndex('retase_reversal_once_uq').on(t.reversesEventId),
  index('retase_counter_idx').on(t.operationDate, t.shiftCode, t.crusherId),
  index('retase_assignment_idx').on(t.assignmentId, t.eventTs),
  index('retase_aa_idx').on(t.aaId, t.eventTs),
  index('retase_actor_recent_idx').on(t.createdBy, t.operationDate, t.shiftCode, t.crusherId, t.eventTs),
  index('retase_report_idx').on(t.reportId, t.eventTs),
]);

export const qcRetaseAllocations = pgTable('qc_retase_allocations', {
  id: uuid('id').primaryKey().defaultRandom(),
  operationDate: date('operation_date').notNull(),
  shiftCode: text('shift_code').notNull(),
  crusherId: uuid('crusher_id').notNull().references(() => crushers.id, { onDelete: 'restrict' }),
  vendorId: uuid('vendor_id').notNull().references(() => vendors.id, { onDelete: 'restrict' }),
  assignmentId: uuid('assignment_id').notNull().references(() => loadingAssignments.id, { onDelete: 'restrict' }),
  sampleId: uuid('sample_id').references(() => rawSamples.id, { onDelete: 'restrict' }),
  mappingStatus: mappingStatusEnum('mapping_status').notNull().default('UNMAPPED'),
  observedRetase: integer('observed_retase').notNull().default(0),
  approvedRetase: integer('approved_retase'),
  consumedRetase: integer('consumed_retase').notNull().default(0),
  candidateCount: integer('candidate_count').notNull().default(0),
  mixId: uuid('mix_id'),
  note: text('note'),
  overrideReason: text('override_reason'),
  reviewRequired: boolean('review_required').notNull().default(false),
  reviewReason: text('review_reason'),
  confirmedBy: uuid('confirmed_by').references(() => users.id, { onDelete: 'restrict' }),
  confirmedAt: timestamp('confirmed_at', { withTimezone: true }),
  consumedAt: timestamp('consumed_at', { withTimezone: true }),
  createdBy: uuid('created_by').references(() => users.id, { onDelete: 'restrict' }),
  updatedBy: uuid('updated_by').references(() => users.id, { onDelete: 'restrict' }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
}, (t) => [
  index('qc_alloc_assignment_idx').on(t.assignmentId, t.mappingStatus),
  index('qc_alloc_sample_idx').on(t.sampleId, t.mappingStatus),
]);
