import { useEffect, useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { createFileRoute } from '@tanstack/react-router';
import type { CreateStockpileLayerRequest, StockpileLotNoMode, StockpileLotStatusFilter } from '@qc/contracts';
import { Modal } from '../../components/modal';
import { createStockpileLayer, getStockpileMap, listStockpileMixes, listWarehouseLayouts, saveReclaimerPosition, updateStockpileLayer, updateStockpileLot } from '../../features/stockpile-map/stockpile-map-api';
import type { StockpileLayer } from '../../features/stockpile-map/stockpile-map-api';
import { positionLabel, SelectedLayerDetails, WarehouseMap } from '../../features/stockpile-map/warehouse-map';
import { businessDateToday } from '../../lib/business-date';

export const Route=createFileRoute('/_authenticated/peta-mutu')({component:PetaMutuPage});
type ColorMode='STATUS'|'PRIMARY'|'PILE';
interface LayerForm {lotId:string;lotNoMode:StockpileLotNoMode;lotNo:string;mixIds:string[];label:string;startPosition:number;endPosition:number;bottomLevel:number;topLevel:number;}
interface LotForm {lotNoMode:StockpileLotNoMode;lotNo:string;}
const blankForm=():LayerForm=>({lotId:'',lotNoMode:'PILE_CYCLE',lotNo:'',mixIds:[],label:'',startPosition:0,endPosition:1,bottomLevel:0,topLevel:1});
const fmt=(value:number,digits=2)=>Number(value).toLocaleString('id-ID',{maximumFractionDigits:digits});

function PetaMutuPage(){
  const today=businessDateToday();const client=useQueryClient();const[layoutId,setLayoutId]=useState('');const[asOf,setAsOf]=useState(today);const[lotStatus,setLotStatus]=useState<StockpileLotStatusFilter>('ACTIVE');const[colorMode,setColorMode]=useState<ColorMode>('STATUS');const[selectedLayerId,setSelectedLayerId]=useState<string|null>(null);const[form,setForm]=useState<LayerForm>(blankForm);const[editingLayer,setEditingLayer]=useState<StockpileLayer|null>(null);const[modalOpen,setModalOpen]=useState(false);const[lotModalOpen,setLotModalOpen]=useState(false);const[lotForm,setLotForm]=useState<LotForm>({lotNoMode:'PILE_CYCLE',lotNo:''});const[message,setMessage]=useState('');const[recPosition,setRecPosition]=useState(0);const[savedRecPosition,setSavedRecPosition]=useState(0);
  const layouts=useQuery({queryKey:['stockpile-map-layouts'],queryFn:listWarehouseLayouts});
  useEffect(()=>{if(!layoutId&&layouts.data?.items[0])setLayoutId(layouts.data.items[0].id);},[layoutId,layouts.data?.items]);
  const map=useQuery({queryKey:['stockpile-map',layoutId,lotStatus,asOf],queryFn:()=>getStockpileMap(layoutId,lotStatus,asOf),enabled:!!layoutId&&!!asOf});
  const data=map.data;const selectedLayer=data?.layers.find(layer=>layer.id===selectedLayerId)??null;const selectedLot=selectedLayer?data?.lots.find(lot=>lot.id===selectedLayer.lotId)??null:null;
  useEffect(()=>{if(!data)return;const position=data.reclaimer?.position??0;setRecPosition(position);setSavedRecPosition(position);if(selectedLayerId&&!data.layers.some(layer=>layer.id===selectedLayerId))setSelectedLayerId(null);},[data?.reclaimer?.eventId,data?.layout.id,data?.asOf,lotStatus]);
  const mixes=useQuery({queryKey:['stockpile-map-mixes',layoutId,modalOpen],queryFn:()=>listStockpileMixes(layoutId,'ALL'),enabled:modalOpen&&!!layoutId});
  const primaryMix=useMemo(()=>mixes.data?.items.find(mix=>form.mixIds.includes(mix.mixId))??null,[mixes.data?.items,form.mixIds]);
  const refresh=async()=>{await Promise.all([client.invalidateQueries({queryKey:['stockpile-map']}),client.invalidateQueries({queryKey:['stockpile-map-mixes']})]);};
  const layerMutation=useMutation({mutationFn:async()=>{
    if(editingLayer)return updateStockpileLayer(editingLayer.id,{expectedVersion:editingLayer.version,mixIds:form.mixIds,label:form.label||null,startPosition:form.startPosition,endPosition:form.endPosition,bottomLevel:form.bottomLevel,topLevel:form.topLevel});
    if(!primaryMix)throw new Error('Pilih minimum satu Mix.');
    const body:CreateStockpileLayerRequest={layoutId,lotId:form.lotId||undefined,logicalPileId:form.lotId?undefined:primaryMix.pileId,pileCycle:form.lotId?undefined:primaryMix.pileCycle,lotNoMode:form.lotNoMode,lotNo:form.lotNoMode==='MANUAL'?form.lotNo||undefined:undefined,mixIds:form.mixIds,label:form.label||null,startPosition:form.startPosition,endPosition:form.endPosition,bottomLevel:form.bottomLevel,topLevel:form.topLevel};return createStockpileLayer(body);
  },onSuccess:async()=>{setModalOpen(false);setEditingLayer(null);setMessage('Layer Peta Mutu tersimpan.');await refresh();},onError:error=>setMessage(error.message)});
  const lotStatusMutation=useMutation({mutationFn:async()=>{if(!selectedLot)throw new Error('Pilih lot.');return updateStockpileLot(selectedLot.id,{status:selectedLot.status==='ACTIVE'?'RECLAIMED':'ACTIVE'});},onSuccess:async()=>{setSelectedLayerId(null);setMessage('Status lot diperbarui.');await refresh();},onError:error=>setMessage(error.message)});
  const lotEditMutation=useMutation({mutationFn:async()=>{if(!selectedLot)throw new Error('Pilih lot.');return updateStockpileLot(selectedLot.id,{lotNoMode:lotForm.lotNoMode,lotNo:lotForm.lotNoMode==='MANUAL'?lotForm.lotNo:undefined});},onSuccess:async()=>{setLotModalOpen(false);setMessage('Nomor lot diperbarui.');await refresh();},onError:error=>setMessage(error.message)});
  const recMutation=useMutation({mutationFn:()=>saveReclaimerPosition({layoutId,position:recPosition,expectedEventId:data?.reclaimer?.eventId??null}),onSuccess:async()=>{setSavedRecPosition(recPosition);setMessage(`Posisi REC disimpan di ${positionLabel(recPosition,data?.layout.postMarks??[])}.`);await refresh();},onError:error=>setMessage(error.message)});
  const openCreate=()=>{setEditingLayer(null);setForm(blankForm());setModalOpen(true);setMessage('');};
  const openEdit=()=>{if(!selectedLayer)return;setEditingLayer(selectedLayer);setForm({lotId:selectedLayer.lotId,lotNoMode:selectedLot?.lotNoMode??'PILE_CYCLE',lotNo:selectedLot?.lotNo??'',mixIds:selectedLayer.mixes.map(mix=>mix.mixId),label:selectedLayer.label??'',startPosition:selectedLayer.startPosition,endPosition:selectedLayer.endPosition,bottomLevel:selectedLayer.bottomLevel,topLevel:selectedLayer.topLevel});setModalOpen(true);setMessage('');};
  const openLotEdit=()=>{if(!selectedLot)return;setLotForm({lotNoMode:selectedLot.lotNoMode,lotNo:selectedLot.lotNo});setLotModalOpen(true);setMessage('');};
  const toggleMix=(mixId:string)=>setForm(current=>({...current,mixIds:current.mixIds.includes(mixId)?current.mixIds.filter(id=>id!==mixId):[...current.mixIds,mixId]}));
  const currentLayout=layouts.data?.items.find(layout=>layout.id===layoutId);
  return <section className="page-stack stockpile-page">
    <div className="page-heading"><div><p className="eyebrow">PHYSICAL STOCKPILE / MIX SUMMARY</p><h1>Peta Mutu</h1><p>Susunan fisik layer Limestone dan Clay, mutu kumulatif, serta posisi reclaimer.</p></div><button className="btn primary" type="button" disabled={!layoutId||data?.isHistorical} title={data?.isHistorical?'Kembali ke tanggal hari ini untuk mengedit.':undefined} onClick={openCreate}>+ Tambah layer</button></div>
    <div className="card stockpile-toolbar"><label><span>Gudang</span><select value={layoutId} onChange={event=>{setLayoutId(event.target.value);setSelectedLayerId(null)}}>{(layouts.data?.items??[]).map(layout=><option key={layout.id} value={layout.id}>{layout.name}</option>)}</select></label><label><span>Tanggal peta</span><div className="stockpile-date-control"><input type="date" value={asOf} max={today} onChange={event=>{setAsOf(event.target.value||today);setSelectedLayerId(null);setMessage('')}}/><button className="btn small" type="button" disabled={asOf===today} onClick={()=>{setAsOf(today);setSelectedLayerId(null)}}>Hari ini</button></div></label><label><span>Tampilan lot</span><select value={lotStatus} onChange={event=>setLotStatus(event.target.value as StockpileLotStatusFilter)}><option value="ACTIVE">Pile aktif</option><option value="RECLAIMED">Sudah direclaim</option><option value="ALL">Semua lot</option></select></label><div><span>Warna layer</span><div className="inline-actions">{(['STATUS','PRIMARY','PILE'] as ColorMode[]).map(mode=><button key={mode} type="button" className={`btn small ${colorMode===mode?'primary':''}`} onClick={()=>setColorMode(mode)}>{mode==='PRIMARY'?(currentLayout?.materialKind==='CL'?'SM':'LSF'):mode==='PILE'?'Pile':'Status'}</button>)}</div></div><span className="toolbar-meta">{data?`${data.counts.activeLots} aktif · ${data.counts.reclaimedLots} reclaimed · ${data.counts.unplacedMixes} Mix belum ditempatkan`:'Memuat...'}</span></div>
    {data?.isHistorical&&<div className="alert stockpile-history-alert"><strong>Snapshot historis {new Date(`${data.asOf}T12:00:00+08:00`).toLocaleDateString('id-ID',{dateStyle:'long'})}</strong><span>Menampilkan kondisi terakhir sampai pukul 23.59 WITA. Mode historis bersifat read-only.</span></div>}
    {message&&<div className={`alert ${message.includes('tersimpan')||message.includes('disimpan')||message.includes('diperbarui')?'success':'error'}`}>{message}</div>}
    {map.isError&&<div className="alert error">{map.error.message}</div>}
    {data&&<><div className="stockpile-main-grid"><div className="card stockpile-map-card"><div className="stockpile-map-heading"><div><strong>{data.layout.name}</strong><small>{data.layout.plantName} · kondisi {data.asOf} · sumbu 0–{fmt(data.layout.axisLength)} · level 0–{fmt(data.layout.maxLevel)}</small></div><div className="reclaimer-save"><span>{positionLabel(recPosition,data.layout.postMarks)}</span><button className="btn small primary" type="button" disabled={data.isHistorical||recMutation.isPending||Math.abs(recPosition-savedRecPosition)<.001} onClick={()=>recMutation.mutate()}>{recMutation.isPending?'Menyimpan...':'Simpan REC'}</button></div></div><WarehouseMap data={data} colorMode={colorMode} selectedLayerId={selectedLayerId} onSelectLayer={layer=>setSelectedLayerId(layer.id)} recPosition={recPosition} onRecPositionChange={setRecPosition} readOnly={data.isHistorical}/><div className="stockpile-legend"><span><i className="legend-box quality-ok"/>Dalam target</span><span><i className="legend-box quality-check"/>Perlu cek</span><span><i className="legend-box quality-no-data"/>No data</span><span className="legend-note">{data.isHistorical?'Snapshot akhir hari WITA.':'Drag REC bebas; tombol panah menggeser 0,1 unit.'}</span></div></div><SelectedLayerDetails layer={selectedLayer} lot={selectedLot} onEdit={openEdit} onEditLot={openLotEdit} onToggleLot={()=>lotStatusMutation.mutate()} readOnly={data.isHistorical}/></div>{!data.layers.length&&<div className="card stockpile-empty"><strong>Belum ada layer pada tampilan ini.</strong><span>{data.isHistorical?'Tidak ada versi layer yang tercatat sampai akhir tanggal tersebut.':'Gunakan “Tambah layer” untuk menempatkan satu atau beberapa Mix Summary pada posisi dan level fisik gudang.'}</span></div>}</>}
    {modalOpen&&data&&<Modal title={editingLayer?'Edit layer fisik':'Tambah layer fisik'} subtitle="Ukuran kotak mengikuti rentang posisi dan level fisik. Satu layer dapat berisi beberapa Mix." onClose={()=>setModalOpen(false)} footer={<><button className="btn" type="button" onClick={()=>setModalOpen(false)}>Batal</button><button className="btn primary" type="button" disabled={layerMutation.isPending||!form.mixIds.length||form.startPosition===form.endPosition||form.topLevel<=form.bottomLevel} onClick={()=>layerMutation.mutate()}>{layerMutation.isPending?'Menyimpan...':'Simpan layer'}</button></>}>
      <div className="form-grid stockpile-layer-form">{!editingLayer&&<><label><span>Lot existing</span><select value={form.lotId} onChange={event=>setForm(current=>({...current,lotId:event.target.value}))}><option value="">— buat / gunakan default dari Mix —</option>{data.lots.filter(lot=>lot.status==='ACTIVE').map(lot=><option key={lot.id} value={lot.id}>{lot.lotNo} · {lot.logicalPileName} · cycle {lot.pileCycle}</option>)}</select></label>{!form.lotId&&<label><span>Mode nomor lot</span><select value={form.lotNoMode} onChange={event=>setForm(current=>({...current,lotNoMode:event.target.value as StockpileLotNoMode}))}><option value="PILE_CYCLE">Default dari Pile Cycle</option><option value="MANUAL">Input manual</option></select></label>}{!form.lotId&&form.lotNoMode==='MANUAL'&&<label><span>Nomor lot manual</span><input value={form.lotNo} onChange={event=>setForm(current=>({...current,lotNo:event.target.value}))}/></label>}</>}
        <label><span>Posisi awal</span><input type="number" min="0" max={data.layout.axisLength} step="0.1" value={form.startPosition} onChange={event=>setForm(current=>({...current,startPosition:Number(event.target.value)}))}/><small>{positionLabel(form.startPosition,data.layout.postMarks)}</small></label><label><span>Posisi akhir</span><input type="number" min="0" max={data.layout.axisLength} step="0.1" value={form.endPosition} onChange={event=>setForm(current=>({...current,endPosition:Number(event.target.value)}))}/><small>{positionLabel(form.endPosition,data.layout.postMarks)}</small></label><label><span>Level bawah</span><input type="number" min="0" max={data.layout.maxLevel} step="0.1" value={form.bottomLevel} onChange={event=>setForm(current=>({...current,bottomLevel:Number(event.target.value)}))}/></label><label><span>Level atas</span><input type="number" min="0" max={data.layout.maxLevel} step="0.1" value={form.topLevel} onChange={event=>setForm(current=>({...current,topLevel:Number(event.target.value)}))}/></label><label className="span-2"><span>Label opsional</span><input value={form.label} placeholder={data.layout.materialKind==='CL'?'Contoh: SM 1.89 AM 2.00':'Contoh: LSF 1276'} onChange={event=>setForm(current=>({...current,label:event.target.value}))}/></label>
        <div className="span-2 stockpile-mix-picker"><div className="mix-picker-heading"><div><strong>Mix Summary</strong><small>Default satu Mix; pilih lebih dari satu untuk layer gabungan.</small></div><span>{form.mixIds.length} dipilih</span></div><div className="mix-picker-grid">{(mixes.data?.items??[]).map(mix=><label key={mix.mixId} className={`mix-picker-item ${form.mixIds.includes(mix.mixId)?'selected':''}`}><input type="checkbox" checked={form.mixIds.includes(mix.mixId)} onChange={()=>toggleMix(mix.mixId)}/><span><b>{mix.mixCode}</b><small>{mix.operationDate} · {mix.pileName} · cycle {mix.pileCycle} · {fmt(mix.totalTon,0)} t</small></span></label>)}{mixes.isLoading&&<span className="table-empty">Memuat Mix Summary...</span>}{!mixes.isLoading&&!mixes.data?.items.length&&<span className="table-empty">Belum ada Mix Summary untuk gudang ini.</span>}</div>{primaryMix&&!form.lotId&&<div className="mix-default-preview">Default lot: <strong>{form.lotNoMode==='PILE_CYCLE'?primaryMix.pileCycle:form.lotNo||'—'}</strong> · {primaryMix.pileName} · cycle {primaryMix.pileCycle}</div>}</div>
      </div>{layerMutation.isError&&<div className="alert error modal-alert">{layerMutation.error.message}</div>}
    </Modal>}
    {lotModalOpen&&selectedLot&&<Modal title="Edit nomor lot" subtitle={`${selectedLot.logicalPileName} · pile cycle ${selectedLot.pileCycle}`} onClose={()=>setLotModalOpen(false)} footer={<><button className="btn" type="button" onClick={()=>setLotModalOpen(false)}>Batal</button><button className="btn primary" type="button" disabled={lotEditMutation.isPending||(lotForm.lotNoMode==='MANUAL'&&!lotForm.lotNo.trim())} onClick={()=>lotEditMutation.mutate()}>{lotEditMutation.isPending?'Menyimpan...':'Simpan nomor lot'}</button></>}>
      <div className="form-grid"><label><span>Sumber nomor lot</span><select value={lotForm.lotNoMode} onChange={event=>setLotForm(current=>({...current,lotNoMode:event.target.value as StockpileLotNoMode}))}><option value="PILE_CYCLE">Default dari Pile Cycle</option><option value="MANUAL">Input manual</option></select></label>{lotForm.lotNoMode==='MANUAL'?<label><span>Nomor lot manual</span><input value={lotForm.lotNo} onChange={event=>setLotForm(current=>({...current,lotNo:event.target.value}))}/></label>:<div className="mix-default-preview">Nomor lot akan mengikuti pile cycle: <strong>{selectedLot.pileCycle}</strong></div>}</div>
      {lotEditMutation.isError&&<div className="alert error modal-alert">{lotEditMutation.error.message}</div>}
    </Modal>}
  </section>;
}
