import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { createFileRoute } from '@tanstack/react-router';
import { MaterialBadge, useMaterial, useMaterialLookups } from '../../features/navigation/material-context';
import { materialNames } from '../../features/navigation/workflow';
import { mixSummary, pileCumulative, qafReport } from '../../features/qc/qc-api';
import { businessMonthToday } from '../../lib/business-date';

export const Route=createFileRoute('/_authenticated/qc-reports')({component:QcReportsPage});
const currentMonth=businessMonthToday;const fmt=(v:unknown,d=2)=>{const n=Number(v);return Number.isFinite(n)?n.toLocaleString('id-ID',{maximumFractionDigits:d}):'—'};
function QcReportsPage(){
  const [tab,setTab]=useState<'summary'|'pile'|'qaf'>('summary');const kind=useMaterial();const [month,setMonth]=useState(currentMonth());const [plantId,setPlantId]=useState('');
  const lookups=useMaterialLookups();
  const dateFrom=`${month}-01`;const lastDay=new Date(Date.UTC(Number(month.slice(0,4)),Number(month.slice(5,7)),0)).getUTCDate();const dateTo=`${month}-${String(lastDay).padStart(2,'0')}`;
  const summary=useQuery({queryKey:['report','summary',kind,month,plantId],queryFn:()=>mixSummary({materialKind:kind,dateFrom,dateTo,plantId:plantId||undefined}),enabled:tab==='summary'});
  const pile=useQuery({queryKey:['report','pile',kind,dateTo,plantId],queryFn:()=>pileCumulative({materialKind:kind,cutoffDate:dateTo,plantId:plantId||undefined}),enabled:tab==='pile'});
  const qaf=useQuery({queryKey:['report','qaf',kind,month,plantId],queryFn:()=>qafReport(kind,month,plantId),enabled:tab==='qaf'&&!!plantId});
  const plants=lookups.data?.plants??[];
  return <section className="page-stack"><div className="page-heading"><div><p className="eyebrow">{materialNames[kind]} / ANALISIS & LAPORAN</p><h1>Laporan QC</h1><p>Ringkasan mixing, akumulasi pile, dan evaluasi mutu harian {materialNames[kind]} dalam satu tempat.</p></div></div>
    <div className="master-tabs report-tabs"><button className={tab==='summary'?'active':''} onClick={()=>setTab('summary')}>Mix Summary<small>Komposisi setiap mixing</small></button><button className={tab==='pile'?'active':''} onClick={()=>setTab('pile')}>Pile Cumulative<small>Akumulasi tonase & mutu</small></button><button className={tab==='qaf'?'active':''} onClick={()=>setTab('qaf')}>QAF Daily<small>Evaluasi mutu harian</small></button></div>
    <div className="card toolbar-card"><MaterialBadge /><input aria-label="Bulan laporan" type="month" value={month} onChange={e=>setMonth(e.target.value)}/><select aria-label="Plant" value={plantId} onChange={e=>setPlantId(e.target.value)}><option value="">Semua plant</option>{plants.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select>{tab==='qaf'&&!plantId&&<span className="toolbar-meta warn-text">QAF membutuhkan Plant.</span>}</div>
    {(lookups.isError||summary.isError||pile.isError||qaf.isError)&&<div className="alert error" role="alert">{lookups.error?.message??summary.error?.message??pile.error?.message??qaf.error?.message}</div>}
    {tab==='summary'&&<div className="card table-card"><div className="table-shell"><table className="native-table qc-wide"><thead><tr><th>Tanggal</th><th>Mix ID</th><th>Plant</th><th>Pile</th><th>Class</th><th>Cycle</th><th>Ton</th><th>SiO2</th><th>Al2O3</th><th>Fe2O3</th><th>CaO</th><th>LSF</th><th>SM</th><th>AM</th><th>NaEq</th><th>R2O3</th></tr></thead><tbody>{(summary.data?.items??[]).map((r:any)=><tr key={r.mixId}><td>{r.operationDate}</td><td><strong>{r.mixCode}</strong></td><td>{r.plantName??'—'}</td><td>{r.pileName}</td><td>{r.className??'—'}</td><td>{r.pileCycle}</td><td>{fmt(r.totalTon)}</td><td>{fmt(r.chemistry.sio2)}</td><td>{fmt(r.chemistry.al2o3)}</td><td>{fmt(r.chemistry.fe2o3)}</td><td>{fmt(r.chemistry.cao)}</td><td>{fmt(r.quality.lsf)}</td><td>{fmt(r.quality.sm)}</td><td>{fmt(r.quality.am)}</td><td>{fmt(r.quality.naeq)}</td><td>{fmt(r.quality.r2o3)}</td></tr>)}{!summary.data?.items.length&&<tr><td colSpan={16} className="table-empty">Tidak ada data.</td></tr>}</tbody></table></div></div>}
    {tab==='pile'&&<div className="card table-card"><div className="table-shell"><table className="native-table qc-wide"><thead><tr><th>Plant</th><th>Pile</th><th>Class</th><th>Cycle</th><th>Total Ton</th><th>LSF</th><th>SM</th><th>AM</th><th>NaEq</th><th>R2O3</th><th>Status</th><th>Last Date</th></tr></thead><tbody>{(pile.data?.items??[]).map((r:any)=><tr key={r.pileId}><td>{r.plantCode??'—'}</td><td>{r.pileName}</td><td>{r.className??'—'}</td><td>{r.pileCycle??'—'}</td><td>{fmt(r.totalTon)}</td><td>{fmt(r.quality?.lsf)}</td><td>{fmt(r.quality?.sm)}</td><td>{fmt(r.quality?.am)}</td><td>{fmt(r.quality?.naeq)}</td><td>{fmt(r.quality?.r2o3)}</td><td><span className={`status-badge ${r.status==='OK'?'success':r.status==='NO DATA'?'muted':'warning'}`}>{r.status}</span></td><td>{r.lastDate??'—'}</td></tr>)}</tbody></table></div></div>}
    {tab==='qaf'&&<div className="card table-card"><div className="table-shell"><table className="native-table qc-wide"><thead><tr><th>Tanggal</th><th>Class Group</th><th>Pile</th><th>Cycle</th><th>Ton</th><th>LSF</th><th>SM</th><th>AM</th><th>NaEq</th><th>R2O3</th><th>Status</th><th>Target</th><th>Mix Ref</th></tr></thead><tbody>{(qaf.data?.items??[]).map((r:any,i:number)=><tr key={`${r.date}-${r.classGroup}-${i}`}><td>{r.date}</td><td>{r.classGroup}</td><td>{r.pileCode??'—'}</td><td>{r.pileCycle??'—'}</td><td>{fmt(r.totalTon)}</td><td>{fmt(r.quality?.lsf)}</td><td>{fmt(r.quality?.sm)}</td><td>{fmt(r.quality?.am)}</td><td>{fmt(r.quality?.naeq)}</td><td>{fmt(r.quality?.r2o3)}</td><td><span className={`status-badge ${r.status==='OK'?'success':r.status==='NO DATA'?'muted':'warning'}`}>{r.status}</span></td><td>{r.target||'—'}</td><td>{r.mixCode??'—'}</td></tr>)}{plantId&&!qaf.data?.items.length&&<tr><td colSpan={13} className="table-empty">Tidak ada data.</td></tr>}</tbody></table></div></div>}
  </section>
}
